bin: rmlink can delete multiple links at once

diff --git a/bin/rmlink b/bin/rmlink
--- a/bin/rmlink
+++ b/bin/rmlink
@@ -4,17 +4,16 @@
 ## bash -n rm-link
 ## shellcheck rm-link
 
-if [ "$#" -ne 1 ]; then
-    echo "Usage: $0 <symlink>" >&2
+if [ "$#" -lt 1 ]; then
+    echo "Usage: $0 <symlink>..." >&2
     exit 1
 fi
 
-symlink="$1"
+for symlink in "$@"; do
+    if [ ! -L "$symlink" ]; then
+        echo "[ERROR] $symlink is not a symlink. Refusing to remove." >&2
+        exit 1
+    fi
+done
 
-if [ -L "$symlink" ]; then
-    rm "$symlink"
-    : # echo "[INF] Symlink $symlink removed."
-else
-    echo "[ERROR] $symlink is not a symlink. Refusing to remove." >&2
-    exit 1
-fi
+rm "$@"
