gxh: sgxsr: improve notification

diff --git a/bin/sgxsr b/bin/sgxsr
--- a/bin/sgxsr
+++ b/bin/sgxsr
@@ -2,14 +2,31 @@
 
 baseLP=$dotf/guix # base-load-path
 
-notify() {
-    # Provide some visual and acoustic notification
-    # See https://chatgpt.com/share/688b4fda-fedc-8012-9c85-068fb6612a43
-    xfconf-query -c xsettings -p /Net/EnableEventSounds -s true
-    xfconf-query -c xsettings -p /Net/EnableInputFeedbackSounds -s true
+beep_once() {
+    (speaker-test --test sine --frequency 440 > /dev/null 2>&1) &
+    local pid=$!
+    sleep 0.22
+    kill -9 "$pid" 2>/dev/null
+    wait "$pid" 2>/dev/null || true  # Prevent exit on wait failure
+}
 
-    for i in $(seq 1 3); do canberra-gtk-play -i message; done
-    notify-send "$@"
+# Acoustic and visual notification
+notify() {
+    if [ "${XDG_CURRENT_DESKTOP}" = "XFCE" ]; then
+        notify-send "$@"
+    fi
+
+    # command is a shell utility. `command --query` works only in fish-shell
+    # speaker-test is in the alsa-utils package
+    if [ "$(command -v speaker-test)" ]; then
+        for i in $(seq 1 3); do beep_once; done
+    else
+        # if [ "$(command -v canberra-gtk-play)" ]; then
+        #     for i in $(seq 1 3); do canberra-gtk-play -i message; done
+        # fi
+        # echo "speaker-test not found"
+        : # for the sake of simplicity just give up ¯\_(ツ)_/¯
+    fi
 }
 
 # GUILE_LOAD_PATH, GUILE_LOAD_COMPILED_PATH have the same values in both
@@ -26,11 +43,11 @@ notify() {
 # chain the commands using '&&', since 'set -e' is used.
 set -e
 
+set -x # Print commands and their arguments as they are executed.
 ## Run this file by (the `~' doesn't work as a value of --load-path):
 # --fallback         fall back to building when the substituter fails
 # -L --load-path
 # -v, --verbosity=LEVEL  use the given verbosity LEVEL
-set -x # Print commands and their arguments as they are executed.
 
 # guix repl \
 #      -L $baseLP/common \
@@ -44,8 +61,13 @@ guix pull --cores=$cores --allow-downgrades \
      --load-path=$baseLP/common \
      --channels=$baseLP/systems/common/syst-channels.scm \
      "$@"
+{ retval="$?"; set +x; } 2>/dev/null
 
 notify "Done" "\`guix pull\` finished"
+
+set -x # Print commands and their arguments as they are executed.
+
+#     --allow-downgrades \
 
 sudo guix system --cores=$cores --verbosity=3 --fallback \
      --load-path=$baseLP/common \
