sgxsr: show 'Using kernel version: ...'

diff --git a/bin/sgxsr b/bin/sgxsr
--- a/bin/sgxsr
+++ b/bin/sgxsr
@@ -1,5 +1,34 @@
 #!/bin/sh
 
+guix_repo=https://git.savannah.gnu.org/git/guix.git
+for d in $HOME/.cache/guix/checkouts/*; do
+    if [ -d "$d" ] && [ ! -L "$d" ]; then
+        # echo "is dir: $d"
+        if git --git-dir=$d/.git remote -v | rg --quiet $guix_repo; then
+            coDir=$d
+            # echo "Guix channel checkout directory: $coDir"
+            break
+        fi
+    fi
+done
+
+# linux_scm=$dgx/gnu/packages/linux.scm
+linux_scm=$coDir/gnu/packages/linux.scm
+
+printf "Analyzing %s ...\n" $linux_scm
+
+llVer=$(rg --no-line-number --replace '$1' \
+               '\(define-public\s+linux-libre-version\s+(.*)\)' $linux_scm)
+# printf "llVer: %s\n" $llVer
+
+ptrn=$(printf '\(define-public\s+%s\s+"(.*)"\)' $llVer)
+# printf "ptrn: %s\n" $ptrn
+
+kernelVer=$(rg --no-line-number --replace '$1' $ptrn $linux_scm)
+printf "Using kernel version: %s\n" $kernelVer
+
+set -e # Exit immediately if a command exits with a non-zero status.
+
 ## Run this file by (the `~' doesn't work as a value of --load-path):
 # --fallback         fall back to building when the substituter fails
 # -L --load-path
