Use #!/usr/bin/env bash

diff --git a/bash/env b/bash/env
--- a/bash/env
+++ b/bash/env
@@ -1,5 +1,9 @@
-#!/bin/bash -e
-# -e stop on error; -x debug
+#!/usr/bin/env bash
+
+# debugging:
+# set -x
+# stop on error:
+# set -e
 
 # setup paths and system variables
 
