bash: noise (hashbang, cleanup)

diff --git a/bash/prompt b/bash/prompt
--- a/bash/prompt
+++ b/bash/prompt
@@ -1,4 +1,10 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# -*- coding:utf-8 -*-
+
+# debugging:
+# set -x
+# stop on error:
+# set -e
 
 # get current branch in git repo
 function parse_git_branch() {
diff --git a/bash/prompt-sexy b/bash/prompt-sexy
--- a/bash/prompt-sexy
+++ b/bash/prompt-sexy
@@ -1,4 +1,11 @@
 #!/usr/bin/env bash
+# -*- coding:utf-8 -*-
+
+# debugging:
+# set -x
+# stop on error:
+# set -e
+
 # Determine what type of terminal we are using for `tput`
 if [[ $COLORTERM = gnome-* && $TERM = xterm ]]  && infocmp gnome-256color >/dev/null 2>&1; then export TERM=gnome-256color
 elif [[ $TERM != dumb ]] && infocmp xterm-256color >/dev/null 2>&1; then export TERM=xterm-256color
